plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.9'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
}

group = 'io.github.murphscall'
version = '0.0.1-SNAPSHOT'
description = 'concert-booking'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    asciidoctorExt
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {

    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-web'

    // SPRING DATA JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // 검증 관련
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // 비밀번호 해싱
    implementation 'org.mindrot:jbcrypt:0.4'

    // Spring Data Redis: 스프링에서 Redis를 쉽게 사용하기 위한 기본 라이브러리
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Redisson: 분산 락을 쉽게 구현하게 도와주는 라이브러리
    implementation 'org.redisson:redisson-spring-boot-starter:3.27.2'

    // devtools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 인메모리 DB
    runtimeOnly 'com.h2database:h2'

    // 마이크로 미터 프로메테우스 구현체
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // RDB
    runtimeOnly 'com.mysql:mysql-connector-j'

    //Jwt
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

ext {
    snippetsDir = file('build/generated-snippets')
}

test {
    outputs.dir snippetsDir
}

asciidoctor {
    inputs.dir snippetsDir
    configurations 'asciidoctorExt'
    dependsOn test
}

bootJar {
    dependsOn asciidoctor
    from("${asciidoctor.outputDir}")
    into 'static/docs'
}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}
